name: Test

on:
  push:
    branches: [ main ]
    paths: [ ".github/workflows/test.yml", "test-projects/**", "index.js", "package.json", "package-lock.json" ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  vitest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: volta-cli/action@v3
    - name: Run npm ci in the root
      run: npm ci
      working-directory: .
    - name: Run vitest
      run: npm run test

  test-projects:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name: [basic, stylistic, react-vite, onsave]
    steps:
    - uses: actions/checkout@v4
    - uses: volta-cli/action@v3
    - name: Run npm ci in the root
      run: npm ci
      working-directory: .
    - name: Run npm ci in a test
      run: npm ci
      working-directory: test-projects/${{ matrix.name }}
    - name: Run eslint
      run: npm run eslint
      working-directory: test-projects/${{ matrix.name }}
