name: Test

on:
  push:
    branches: [ main ]
    paths: [ ".github/workflows/test.yml", "tests/**", "index.js", "package.json", "package-lock.json" ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        name: [basic, stylistic, react-vite, import]

    steps:
    - uses: actions/checkout@v3
    - uses: volta-cli/action@v3
    - name: Run npm ci in the root
      run: npm ci
      working-directory: .
    - name: Run npm ci in a test
      run: npm ci
      working-directory: tests/${{ matrix.name }}
    - name: Run eslint
      run: npm run eslint
      working-directory: tests/${{ matrix.name }}
